/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fungsi;
import static fungsi.Menuku.label2;
import static fungsi.Menuku.label21;
import static fungsi.Menuku.labelku;
import java.sql.ResultSet;
import java.sql.Statement;
//import static master.rekam_catatan.labelrekam1;
//import static master.rekam_catatan.labelrekam2;
//import static master.rekam_catatan.labelrekam4;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import master.catatan;
import master.login;
import master.pengguna;
import static master.pengguna1.tambah1;
import master.rekam_catatan;

/**
 *
 * @author USER
 */
public class Menuku1 extends javax.swing.JFrame {

    /**
     * Creates new form Menuku1
     */
    public Menuku1() {
        initComponents();
        isidata.setVisible(false);
        catatan.setVisible(false);
        icon.setVisible(false);
        bpengguna.setVisible(false);
        
        label2.setText("NIK: " + label2.getText());
        label21.setText("ID: " + label21.getText());
        labelku.setText("Nama: " + labelku.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        catatan = new javax.swing.JButton();
        icon = new javax.swing.JButton();
        isidata = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bpengguna = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lnama = new javax.swing.JLabel();
        idpengguna = new javax.swing.JLabel();
        lnik = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        catatan.setBackground(new java.awt.Color(0, 0, 153));
        catatan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        catatan.setForeground(new java.awt.Color(255, 255, 255));
        catatan.setText("CATATAN REKAM PERJALANAN");
        catatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catatanActionPerformed(evt);
            }
        });

        icon.setBackground(new java.awt.Color(0, 0, 153));
        icon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        icon.setForeground(new java.awt.Color(255, 255, 255));
        icon.setText("ICON LAIN");
        icon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconActionPerformed(evt);
            }
        });

        isidata.setBackground(new java.awt.Color(0, 0, 153));
        isidata.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        isidata.setForeground(new java.awt.Color(255, 255, 255));
        isidata.setText("ISI DATA PERJALANAN");
        isidata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isidataActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GUNAWAN WIDYA NUGRAHA - 10 - XII-RPL 2");

        bpengguna.setText("jButton1");
        bpengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bpenggunaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isidata, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bpengguna))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catatan, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catatan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isidata, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpengguna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(24, 24, 24))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fungsi/images.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelku.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelku.setForeground(new java.awt.Color(255, 255, 255));
        labelku.setText("outputnama");
        labelku.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("outputnik");

        label21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label21.setForeground(new java.awt.Color(255, 255, 255));
        label21.setText("outputid");

        lnama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lnama.setForeground(new java.awt.Color(255, 255, 255));
        lnama.setText("NAMA");

        idpengguna.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idpengguna.setForeground(new java.awt.Color(255, 255, 255));
        idpengguna.setText("ID PENGGUNA");

        lnik.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lnik.setForeground(new java.awt.Color(255, 255, 255));
        lnik.setText("NIK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnama, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnik, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idpengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2)
                    .addComponent(label21)
                    .addComponent(labelku))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lnama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lnik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(idpengguna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jMenu1.setText("Dashboard");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Catatan Perjalanan");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Isi Data");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Keluar");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catatanActionPerformed
        try{
            Statement stt = (Statement)koneksi.GetConnection().createStatement();
            ResultSet result = stt.executeQuery("select * from tb_pengguna where id_pengguna = '"+label21.getText() + "'");
            if(result.next()){
                idpengguna.setText(result.getString(1));
                lnik.setText(result.getString(2));
                lnama.setText(result.getString(3));
                new catatan().setVisible(true);
                this.dispose();
            }else{
                // JOptionPane.showMessageDialog(rootPane, "MOHON MAAF DATA ANDA BLM TERDAFTAR SILAHKAN KLIK TOMBOL KIRI == DAFTAR PENGGUNA==.");
            }
        }catch(Exception e){
            // JOptionPane.showMessageDialog(rootPane, "Login gagal.");
        }
    }//GEN-LAST:event_catatanActionPerformed

    private void iconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconActionPerformed

    private void isidataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isidataActionPerformed
        // TODO add your handling code here:
        try{
            Statement stt = (Statement)koneksi.GetConnection().createStatement();
            ResultSet result = stt.executeQuery("select * from tb_pengguna where nik = '"+ label2.getText() +
                "'");
            if(result.next()){
                //            labelrekam1.setText(result.getString(3));
                //            labelrekam2.setText(result.getString(2));
                //            labelrekam4.setText(result.getString(1));
                new rekam_catatan().setVisible(true);
                this.dispose();
            }else{
                // JOptionPane.showMessageDialog(rootPane, "MOHON MAAF DATA ANDA BLM TERDAFTAR, SILAHKAN KLIK TOMBOL KIRI == DAFTAR PENGGUNA==.");
            }
        }catch(Exception e){
            //JOptionPane.showMessageDialog(rootPane, "Login gagal.");
        }
    }//GEN-LAST:event_isidataActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        isidata.setVisible(true);
        catatan.setVisible(true);
        icon.setVisible(true);
        bpengguna.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        try{
            Statement stt = (Statement)koneksi.GetConnection().createStatement();
            ResultSet result = stt.executeQuery("select * from tb_pengguna where nik = '"+ label2.getText() +"'");
            if(result.next()){
//            labelrekam1.setText(result.getString(3));
//            labelrekam2.setText(result.getString(2));
//            labelrekam4.setText(result.getString(1));
            new rekam_catatan().setVisible(true);
            this.dispose();
            }else{
            JOptionPane.showMessageDialog(rootPane, "MOHON MAAF DATA ANDA BLM TERDAFTAR, SILAHKAN KLIK TOMBOL KIRI == DAFTAR PENGGUNA==.");
            }
            }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Login gagal.");
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        try{
            Statement stt = (Statement)koneksi.GetConnection().createStatement();
            ResultSet result = stt.executeQuery("select * from tb_pengguna where id_pengguna = '"+label21.getText() + "'");
            if(result.next()){
            new catatan().setVisible(true);
            idpengguna.setText(result.getString(1));
            lnik.setText(result.getString(2));
            lnama.setText(result.getString(3));
            new catatan().setVisible(true);
            this.dispose();
            }else{
            // JOptionPane.showMessageDialog(rootPane, "MOHON MAAF DATA ANDA BLM TERDAFTAR, SILAHKAN KLIK TOMBOL KIRI == DAFTAR PENGGUNA==.");
            }
            }catch(Exception e){
            // JOptionPane.showMessageDialog(rootPane, "Login gagal.");
        }
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void bpenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpenggunaMouseClicked
        // TODO add your handling code here:
        new pengguna().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bpenggunaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuku1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuku1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuku1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuku1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuku1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bpengguna;
    private javax.swing.JButton catatan;
    private javax.swing.JButton icon;
    private javax.swing.JLabel idpengguna;
    private javax.swing.JButton isidata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static final javax.swing.JLabel label2 = new javax.swing.JLabel();
    public static final javax.swing.JLabel label21 = new javax.swing.JLabel();
    public static final javax.swing.JLabel labelku = new javax.swing.JLabel();
    private javax.swing.JLabel lnama;
    private javax.swing.JLabel lnik;
    // End of variables declaration//GEN-END:variables
}
