/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package master;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static master.pengguna1.hapus;
import static master.pengguna1.simpan;
import static master.pengguna1.ubah;

/**
 *
 * @author USER
 */
public class catatan1 extends javax.swing.JFrame {

    String sql;
    String Status1;
    public Connection con;
    public Statement stt;
    public ResultSet rs;
    /**
     * Creates new form catatan1
     */
    public catatan1() {
        initComponents();
        setDefaultTable();
        tabel.setModel(tblModel);
        Tabel(tabel,new int[]{80,100,100,80,90,80,90});
        mati();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
        ImageIcon ico = new ImageIcon("src/icon/patient.png");
        setIconImage(ico.getImage());
        // jk.setSelectedItem("==Pilih Jenis Kelamin==");
        jk.setModel(new DefaultComboBoxModel(new String[] {"Laki-Laki","Perempuan"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void setDefaultTable() {
        String hubung = "jdbc:mysql://localhost:3306/rekamjejak_gunawan";
        try {
        Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        Connection kon = DriverManager.getConnection(hubung,"root","");
        Statement stt = kon.createStatement();
        String SQL = "Select * from tb_catatan";
         ResultSet res = stt.executeQuery(SQL);
        while(res.next()) {
        data[0] = res.getString(1);
        data[1] = res.getString(2);
        data[2] = res.getString(3);
        data[3] = res.getString(4);
        data[4] = res.getString(5);
        data[5] = res.getString(6);
        tblModel.addRow(data);
         }
        res.close();
        stt.close();
        kon.close();
        } catch(Exception exc) {
        System.err.println(exc.getMessage());
        }
    }
    
    private javax.swing.table.DefaultTableModel tblModel = getDefaultTabelModel();
    
    private void Tabel(javax.swing.JTable tb, int lebar[]) {
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        int kolom=tb.getColumnCount();
        for(int i=0;i < kolom;i++) {
        javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
        tbc.setPreferredWidth(lebar[i]);
        tb.setRowHeight(17);
        }
        }
        private javax.swing.table.DefaultTableModel getDefaultTabelModel() {
        return new javax.swing.table.DefaultTableModel(
        new Object [][]{},
        new String []{"Id Pengguna","NIK","Nama Pengguna","Alamat Pengguna","Jenis Kelamin"}
        ){
        boolean[] canEdit = new boolean []{
        false,false,false,false,false,false,false
        };
        public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
        }
        };
    }
    
        int row=0;
    public void Tampil(){
        row = tabel.getSelectedRow();
        idpengguna.setText(tblModel.getValueAt(row,0).toString());
        nik1.setText(tblModel.getValueAt(row, 1).toString());
        namapengguna.setText(tblModel.getValueAt(row, 2).toString());
        alamatpengguna.setText(tblModel.getValueAt(row, 3).toString());
        jk.setSelectedItem(tblModel.getValueAt(row, 4).toString());
    }
    
    public void mati (){
        idpengguna.setEnabled(false);
        nik1.setEnabled(false);
        namapengguna.setEnabled(false);
        alamatpengguna.setEnabled(false);
        jk.setEnabled(false);
        simpan.setEnabled(false);
        hapus.setEnabled(false);
        ubah.setEnabled(false);
    }
    
    public void hidup (){
        //no_pasien.setEnabled(true);
        idpengguna.setEnabled(true);
        nik1.setEnabled(true);
        namapengguna.setEnabled(true);
        alamatpengguna.setEnabled(true);
        jk.setEnabled(true);
        simpan.setEnabled(true);
        hapus.setEnabled(true);
        ubah.setEnabled(true);
    }

    public void bersih(){
        idpengguna.setText("");
        nik1.setText("");
        namapengguna.setText("");
        alamatpengguna.setText("");
        jk.setModel(new DefaultComboBoxModel(new String[] {"Laki-Laki","Perempuan"}));
    }

    public void autokode(){
    String hubung = "jdbc:mysql://localhost/rekamjejak_gunawan";

    try {
        Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        Connection kon = DriverManager.getConnection(hubung, "root", "");
        Statement stmt = kon.createStatement();
        String SQL = "SELECT IFNULL(MAX(CAST(RIGHT(id_pengguna, 3) AS SIGNED)), 0) AS no FROM tb_pengguna";
        ResultSet rs = stmt.executeQuery(SQL);
        if (rs.next()) {
            int auto_nis = rs.getInt("no") + 1;
            String no = String.valueOf(auto_nis);
            idpengguna.setText(no);
        }
        rs.close();
        stmt.close();
    } catch (Exception e) {
        e.printStackTrace(); // Handle the exception appropriately, e.g., logging it.
    }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatpengguna = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        nik1 = new javax.swing.JTextField();
        jk = new javax.swing.JComboBox();
        namapengguna = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idpengguna = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        simpan.setBackground(new java.awt.Color(0, 255, 255));
        simpan.setForeground(new java.awt.Color(255, 255, 255));
        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(0, 255, 255));
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        ubah.setBackground(new java.awt.Color(0, 255, 255));
        ubah.setForeground(new java.awt.Color(255, 255, 255));
        ubah.setText("UBAH");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        alamatpengguna.setColumns(20);
        alamatpengguna.setRows(5);
        jScrollPane1.setViewportView(alamatpengguna);

        keluar.setBackground(new java.awt.Color(0, 255, 255));
        keluar.setForeground(new java.awt.Color(255, 255, 255));
        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        tambah1.setBackground(new java.awt.Color(0, 255, 255));
        tambah1.setForeground(new java.awt.Color(255, 255, 255));
        tambah1.setText("TAMBAH");
        tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATA PENGGUNA REGISTRASI");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        nik1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nik1ActionPerformed(evt);
            }
        });

        jk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki - Laki", "Perempuan" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INPUT PENGGUNA BARU");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAMA PENGGUNA");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ALAMAT PENGGUNA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIK");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("JENIS KELAMIN");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID PENGGUNA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gunawan Widya Nugraha - 10 - XII RPL 2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(idpengguna)
                                .addComponent(nik1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(namapengguna, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tambah1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idpengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namapengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambah1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String data[]=new String[7];
    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String ObjButtons[] = {"Yes","No"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Simpan Data?","Message",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){
            try {
                String hubung="jdbc:mysql://localhost:3306/rekamjejak_gunawan";
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                Connection kon=DriverManager.getConnection(hubung,"root","");
                Statement stt=kon.createStatement();
                String SQL="insert into tb_pengguna values('"+idpengguna.getText()+"','"+nik1.getText()+"','"+namapengguna.getText()+"','"+alamatpengguna.getText()+"','"+jk.getSelectedItem()+"')";
                stt.executeUpdate(SQL);
                data[0]=idpengguna.getText();
                data[1]=nik1.getText().toString();
                data[2]=namapengguna.getText().toString();
                data[3]=alamatpengguna.getText().toString();
                data[4]=jk.getSelectedItem().toString();
                tblModel.insertRow(0,data);
                bersih();
                stt.close();
                kon.close();
            }catch(Exception exc) { System.err.println(exc.getMessage());
            }
            bersih();
            mati();
            tambah1.setEnabled(true);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        String ObjButtons[] = {"Yes","No"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Hapus Data?","Message",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){
            try {
                String hubung = "jdbc:mysql://localhost:3306/rekamjejak_gunawan";
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                Connection kon = DriverManager.getConnection(hubung,"root","");
                Statement stt = kon.createStatement();
                String SQL = "delete from tb_pengguna where id_pengguna='"+idpengguna.getText()+"'";
                stt.executeUpdate(SQL);
                tblModel.removeRow(row);
            } catch(Exception exc){
                System.err.println(exc.getMessage());
            }
            bersih();
            mati();
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        String ObjButtons[] = {"Yes","No"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Ubah Data?","Message",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){
            try{
                String hubung = "jdbc:mysql://localhost:3306/rekamjejak_gunawan";
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                Connection kon = DriverManager.getConnection(hubung,"root","");
                Statement stt = kon.createStatement();
                String SQL = "update tb_pengguna set nik= '"+nik1.getText()+"'," +" nama_pengguna='"+namapengguna.getText()+"'," +" alamat_pengguna='"+alamatpengguna.getText()+"'," +" jenis_kelamin='"+jk.getSelectedItem()+"'" +" where id_pengguna= '"+idpengguna.getText()+"'";
                stt.executeUpdate(SQL);
                data[0] = idpengguna.getText();
                data[1] = nik1.getText();
                data[2] = namapengguna.getText();
                data[3] = alamatpengguna.getText();
                data[4] = jk.getSelectedItem().toString();
                tblModel.removeRow(row);
                tblModel.insertRow(row, data);
                bersih();
                mati();
                simpan.setEnabled(false);
                tambah1.setEnabled(true);
                stt.close();
                kon.close();
            }catch(Exception exc){
                System.err.println(exc.getMessage());
            }
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah1ActionPerformed
        // TODO add your handling code here:
        hidup();
        bersih();
        nik1.requestFocus();
        idpengguna.setEnabled(false);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        autokode();
    }//GEN-LAST:event_tambah1ActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2) {
            Tampil();
            hidup();
            simpan.setEnabled(false);
            nik1.requestFocus();
            idpengguna.setEnabled(false);
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void nik1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nik1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nik1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(catatan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(catatan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(catatan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(catatan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new catatan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatpengguna;
    public static final javax.swing.JButton hapus = new javax.swing.JButton();
    private javax.swing.JTextField idpengguna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jk;
    public static final javax.swing.JButton keluar = new javax.swing.JButton();
    private javax.swing.JTextField namapengguna;
    private javax.swing.JTextField nik1;
    public static final javax.swing.JButton simpan = new javax.swing.JButton();
    private javax.swing.JTable tabel;
    public static final javax.swing.JButton tambah1 = new javax.swing.JButton();
    public static final javax.swing.JButton ubah = new javax.swing.JButton();
    // End of variables declaration//GEN-END:variables
}
