package master;
import fungsi.Menuku;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.text.ParseException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import java.sql.SQLException;

import javax.swing.JButton;
/**
 *
 * @author USER
 */
public class pengguna extends javax.swing.JFrame {

    String sql;
    String Status1;
    public Connection con;
    public Statement stt;
    public ResultSet rs;
    
    /**
     * Creates new form pengguna
     */
    
    pengguna myPengguna = new pengguna();
    javax.swing.JButton myButton = myPengguna.tambah1;
    
    public pengguna() {
        initComponents();
        setDefaultTable();
        tabel.setModel(tblModel);
        Tabel(tabel,new int[]{80,100,100,80,90,80,90});
        mati();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
        ImageIcon ico = new ImageIcon("src/icon/patient.png");
        setIconImage(ico.getImage());
        // jk.setSelectedItem("==Pilih Jenis Kelamin==");
        jk.setModel(new DefaultComboBoxModel(new String[] {"Laki-Laki","Perempuan"}));
    }
    
    pengguna(String string, String string0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void setDefaultTable() {
        String hubung = "jdbc:mysql://localhost:3306/rekamjejak_gunawan";
        try {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection kon = DriverManager.getConnection(hubung,"root","");
        Statement stt = kon.createStatement();
        String SQL = "Select * from tb_pengguna";
         ResultSet res = stt.executeQuery(SQL);
        while(res.next()) {
        data[0] = res.getString(1);
        // data[1] = res.getString(2);
        data[2] = res.getString(3);
        data[3] = res.getString(4);
        data[4] = res.getString(5);
        tblModel.addRow(data);
         }
        res.close();
        stt.close();
        kon.close();
        } catch(Exception exc) {
        System.err.println(exc.getMessage());
        }
    }
    
    private javax.swing.table.DefaultTableModel tblModel = getDefaultTabelModel();

    private void Tabel(javax.swing.JTable tb, int lebar[]) {
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        int kolom=tb.getColumnCount();
        for(int i=0;i < kolom;i++) {
        javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
        tbc.setPreferredWidth(lebar[i]);
        tb.setRowHeight(17);
        }
        }
        private javax.swing.table.DefaultTableModel getDefaultTabelModel() {
        return new javax.swing.table.DefaultTableModel(
        new Object [][]{},
        new String []{"Id Pengguna","Nik","Nama Pengguna","Alamat Pengguna","Jenis Kelamin"}
        ){
        boolean[] canEdit = new boolean []{
        false,false,false,false,false,false,false
        };
        public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
        }
        };
    }
    /**
    *  This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idpengguna = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nik1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        namapengguna = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatpengguna = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jk = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        tambah1 = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("INPUT PENGGUNA BARU");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID PENGGUNA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("NIK");

        nik1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nik1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("NAMA PENGGUNA");

        alamatpengguna.setColumns(20);
        alamatpengguna.setRows(5);
        jScrollPane1.setViewportView(alamatpengguna);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("ALAMAT PENGGUNA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("JENIS KELAMIN");

        jk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki - Laki", "Perempuan" }));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        tambah1.setText("TAMBAH");
        tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah1ActionPerformed(evt);
            }
        });

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        ubah.setText("UBAH");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("DATA PENGGUNA UDH REGRISTRASI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(tambah1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simpan)
                        .addGap(28, 28, 28)
                        .addComponent(hapus)
                        .addGap(33, 33, 33)
                        .addComponent(ubah)
                        .addGap(44, 44, 44)
                        .addComponent(keluar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(idpengguna)
                                .addComponent(nik1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(namapengguna, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(idpengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namapengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(tambah1)
                    .addComponent(hapus)
                    .addComponent(ubah)
                    .addComponent(keluar))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String data[]=new String[7];
    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String ObjButtons[] = {"Yes","No"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Simpan Data?","Message",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){
        try {
        String hubung="jdbc:mysql://localhost:3306/rekamjejak_gunawan";
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection kon=DriverManager.getConnection(hubung,"root","");
        Statement stt=kon.createStatement();
        String SQL="insert into tb_pengguna values('"+idpengguna.getText()+"','"+nik1.getText()+"','"+namapengguna.getText()+"','"+alamatpengguna.getText()+"','"+jk.getSelectedItem()+"')";
        stt.executeUpdate(SQL);
        data[0]=idpengguna.getText();
        data[1]=nik1.getText().toString();
        data[2]=namapengguna.getText().toString();
        data[3]=alamatpengguna.getText().toString();
        data[4]=jk.getSelectedItem().toString();
        tblModel.insertRow(0,data);
        bersih();
        stt.close();
        kon.close();
        }catch(Exception exc) { System.err.println(exc.getMessage());
        }
        bersih(); 
        mati();
        tambah1.setEnabled(true);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        String ObjButtons[] = {"Yes","No"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Hapus Data?","Message",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){
        try {
        String hubung = "jdbc:mysql://localhost:3306/rekamjejak_gunawann";
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection kon = DriverManager.getConnection(hubung,"root","");
        Statement stt = kon.createStatement();
        String SQL = "delete from tb_pengguna where id_pengguna='"+idpengguna.getText()+"'";
        stt.executeUpdate(SQL);
        tblModel.removeRow(row);
        } catch(Exception exc){
        System.err.println(exc.getMessage());
        }
        bersih(); 
        mati();
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        String ObjButtons[] = {"Yes","No"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Ubah Data?","Message",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){
        try{
        String hubung = "jdbc:mysql://localhost:3306/tb_perjalanan";
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection kon = DriverManager.getConnection(hubung,"root","");
        Statement stt = kon.createStatement();
        String SQL = "update tb_pengguna set nik= '"+nik1.getText()+"',"+" nama_pengguna='"+namapengguna.getText()+"',"+"alamat_pengguna='"+alamatpengguna.getText()+"',"+"jenis_kelamin='"+jk.getSelectedItem()+"',"+"' where id_pengguna= '"+idpengguna.getText()+"'";
        stt.executeUpdate(SQL);
        data[0] = idpengguna.getText();
        data[1] = nik1.getText();
        data[2] = namapengguna.getText();
        data[3] = alamatpengguna.getText();
        data[4] = jk.getSelectedItem().toString();
        tblModel.removeRow(row);
        tblModel.insertRow(row, data);
        bersih(); 
        mati();
        simpan.setEnabled(false);
        tambah1.setEnabled(true);
        stt.close();
        kon.close();
        }catch(Exception exc){
        System.err.println(exc.getMessage());
        }
        }

    }//GEN-LAST:event_ubahActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            Tampil();
            hidup();
            simpan.setEnabled(false);
            nik1.requestFocus();
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah1ActionPerformed
        // TODO add your handling code here:
        hidup();
        bersih();
        nik1.requestFocus();
        idpengguna.setEnabled(false);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        //autokode();
    }//GEN-LAST:event_tambah1ActionPerformed

    private void nik1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nik1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nik1ActionPerformed

    int row=0;
    public void Tampil(){
        row = tabel.getSelectedRow();
        idpengguna.setText(tblModel.getValueAt(row,0).toString());
        nik1.setText(tblModel.getValueAt(row, 1).toString());
        namapengguna.setText(tblModel.getValueAt(row, 2).toString());
        alamatpengguna.setText(tblModel.getValueAt(row, 3).toString());
        jk.setSelectedItem(tblModel.getValueAt(row, 4).toString());
    }
    
    public void mati (){
        idpengguna.setEnabled(false);
        nik1.setEnabled(false);
        namapengguna.setEnabled(false);
        alamatpengguna.setEnabled(false);
        jk.setEnabled(false);
        simpan.setEnabled(false);
        hapus.setEnabled(false);
        ubah.setEnabled(false);
    }
    
    public void hidup (){
        //no_pasien.setEnabled(true);
        idpengguna.setEnabled(true);
        nik1.setEnabled(true);
        namapengguna.setEnabled(true);
        alamatpengguna.setEnabled(true);
        jk.setEnabled(true);
        simpan.setEnabled(true);
        hapus.setEnabled(true);
        ubah.setEnabled(true);
    }

    public void bersih(){
        idpengguna.setText("");
        nik1.setText("");
        namapengguna.setText("");
        alamatpengguna.setText("");
        jk.setModel(new DefaultComboBoxModel(new String[] {"Laki-Laki","Perempuan"}));
    }

    public void autokode(){
    String hubung = "jdbc:mysql://localhost:3306/rekamjejak_gunawan";
    try{
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection kon = DriverManager.getConnection(hubung,"root","");
        Statement stmt = kon.createStatement();
        String SQL = "SELECT MAX(right(id_pengguna,2)) AS no FROM tb_pengguna";
        ResultSet rs = stmt.executeQuery(SQL);
        while(rs.next())
    {
        
    if(rs.first() == false) {
        idpengguna.setText("01");
    } else {
        rs.last();
        int auto_nis = rs.getInt(1) + 1;
        String no = String.valueOf(auto_nis);
        int noLong = no.length();
        //MENGATUR jumlah 0
        for(int a=0;a<3-noLong;a++) {
            no = "0" + no;
        }
        idpengguna.setText("01" + no);
        }
    }
        rs.close();
        stmt.close();
    }
    catch (Exception e){
        JOptionPane.showMessageDialog(this, "ERROR: \n" + e.toString(), "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengguna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatpengguna;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idpengguna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jk;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField namapengguna;
    private javax.swing.JTextField nik1;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah1;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
